### ISSUE TITLE
A call to bootbox scrolls page in iframe to scroll to top

### ISSUE THREAD

**Issue by Ben76** [makeusabrew/bootbox#638] opened 2017-11-25 06:09 UTC
I am having problems when I call bootbox.confirm from a page in a iframe. Bootbox modal shows up on the top of the page. Does not consider scroll at all. I have other modals that work perfectly fine. When I replace bootbox with a simple javascript alert, then too it works without any scroll.

**Comment by tiesont** [comment] 2017-11-25 19:54
Native alerts don't behave the same way that markup-based modals work, so I'm not sure what the intended point of that comparison is. 

Bootbox, at it's core, is just building Bootstrap modals, which (through Bootstrap 4 Beta 2) always show up at the top of the page. If your page is actually scrolling, it's probably because you're triggering it with an anchor tag (something like `<a href="#">Foo</a>`) but not preventing the click event. 

It's also worth pointing out that Bootstrap modals (and therefore Bootbox modals) are [asynchronous](http://getbootstrap.com/docs/4.0/components/modal/#methods) methods - they can't block the flow of execution of your code, unlike native alerts.

If you think that there is an actual bug, please add an example that demonstrates what you're seeing.

**Comment by Ben76** [comment] 2017-11-27 06:32
Thanks for your response.

I am sharing details of the website with credentials

www.trulysocial.in
Id: test@test.com
pw: 1234a

Click on 'Test Group' on the left.
Next, click on the settings icon against Test-101. (in the middle column - this is actually a page in a iframe) You can find 4 links. The first 2 links work fine (Modify, Share Date).

The next 2 links, I am calling bootstrap.confirm. But, the page scrolls to the top. 

I  am infact calling e.preventDefault(). Yet, the page scrolls to the top.

**Comment by tiesont** [comment] 2017-11-28 20:52
Sorry, I'm not logging into some random site. If you can create an isolated example that reproduces the problem, I'll check it out, but otherwise, sorry, this isn't a Bootbox bug.

**Comment by Ben76** [comment] 2017-12-27 17:31
Please check this URL - http://pb.cloudtechpro.in/test.aspx

**Comment by tiesont** [comment] 2017-12-27 23:16
No. I will review something embedded directly in an issue, or on a well-known site like jsFiddle or Bootply, but I'm not visiting anything else. You need to be able to isolate this to something that doesn't require your whole project to reproduce. If you can do that, I'll reopen this issue. For now, I'm closing as not-reproducible.

**Closed by tiesont** 2017-12-27 23:16 UTC
Labels: Needs example
