### ISSUE TITLE
event not working when set animate to false

### ISSUE THREAD

**Issue by erwinheldy** [makeusabrew/bootbox#733] opened 2019-11-07 05:00 UTC
Demo: https://o4rsk.csb.app/

**Comment by tiesont** [comment] 2019-11-16 23:59
I'll need you to elaborate on what the actual issue you're having seems to be, plus either a jsFiddle or enough code for me to reproduce, within your issue. Otherwise, I'll be closing this.

**Comment by erwinheldy** [comment] 2019-11-17 13:54
here is the jsFiddle: https://jsfiddle.net/qf2g4mrs/
when the animate option is set to true, the "shown.bs.modal" event will work and run the alert ("shown"). But when the animate option is set to false, the event doesn't work so it doesn't run an alert ("shown")

**Comment by tarlepp** [comment] 2019-11-17 16:00
That might be Bootstrap bug/feature;
https://getbootstrap.com/docs/4.0/components/modal/#events

shown.bs.modal | This event is fired when the modal has been made visible to the user (will wait for CSS transitions to complete). If caused by a click, the clicked element is available as the relatedTarget property of the event.
-- | --

**Comment by erwinheldy** [comment] 2019-11-18 01:20
Bootstrap event works fine, check the following fiddle:
https://jsfiddle.net/v68gs3fd/

**Comment by tiesont** [comment] 2019-11-18 01:54
Interesting. All we do differently when `animate: false` is set is omit the `.fade` class (so the CSS transitions aren't applied) from the modal.

**Comment by tiesont** [comment] 2019-11-18 02:10
Okay, figured this out: it's a timing issue: https://jsfiddle.net/b15ochuy/.

Basically, by the time your 

```js
modal.on('shown.bs.modal, ()=>{ /* ... */ });
```

code is being applied, the `shown.bs.modal` event has already occurred. I verified this by adding a simple console.log to [here](https://github.com/makeusabrew/bootbox/blob/master/bootbox.js#L398), which showed me that the event _was_ being called. If you then set the `show` option to false, and manually trigger the dialog (as shown in the fiddle above), then you see the alert.

I'm assuming this works with regular Bootstrap due to the DOM elements already being present when the `.on()` handler is being added. We're creating the modals on the fly, so the elements aren't there yet in your original fiddle, which means there's nothing to attach.

Not sure if it's possible to attach the event to anything else, like '.body`, and then filter down to the `.bootbox` element - we don't add the modal to the page at any point.

**Comment by tiesont** [comment] 2019-11-19 09:35
@tarlepp What's your thoughts on adding some optional event hooks? We could allow something like:

```js
bootbox.alert({
    message: 'I have a custom shown handler!',
    onShown: function(e) {
        /* code to execute when shown.bs.modal is raised */
    }
});
```

That's a bit cleaner than:


```js
let dialog = bootbox.alert({
    message: 'I have a custom shown handler!'
});

dialog.on('shown.bs.modal', function(e) {
    /* code to execute when shown.bs.modal is raised */
})
```

I think that would solve this problem, since the custom shown handler gets wired up before the dialog is actually shown. We could add options for shown and hidden (and maybe hide?) - show isn't possible, just based on how bootbox works internally.

**Comment by tiesont** [comment] 2019-11-20 04:53
@erwinheldy If you want to be a test case, here's a gist with the function options I suggested: https://gist.github.com/tiesont/ffeb904d55e7203c77376d35edd2c304 - I need to add valid tests before I'd be comfortable pushing this into master.

**Comment by erwinheldy** [comment] 2019-11-20 09:18
Just try a simple test: https://jsfiddle.net/ap9ot14u/4/
I tried opening and closing the modal several times.
The alert function runs well every event is called, but not with the `$('#groupName').focus();` function. it only runs once

**Comment by tiesont** [comment] 2019-11-20 20:57
The function **is** actually being called each time - add a `console.log('shown')` to the function, and you'll see the message multiple times. As to why the focus isn't being given, I don't know. This is a work-in-progress, so it's going to take me some time to work this out, as I find time to work on it.

**Comment by tiesont** [comment] 2019-11-21 01:32
@erwinheldy There was a bug in the "cleanup" function, which I think I've fixed - here's an update to your fiddle: https://jsfiddle.net/9egd5kt3/

The gist has been updated as well.

**Comment by erwinheldy** [comment] 2019-11-21 02:31
Awesome. I can confirm that your gist can resolve this issue.

**Comment by tiesont** [comment] 2019-11-21 02:46
@erwinheldy Cool beans. I'll see if I can find some time to update master and the test suite. For now, if you are okay with just manually updating your local copy with the code from the gist, here's the function hooks you can use:

- `onShow`
- `onShown`
- `onHide`
- `onHidden`

I'm going to close this in favor of adding a new feature issue, #737

**Closed** 2019-12-21 20:38 UTC
Labels: Bootstrap, Bug?
