### ISSUE TITLE
Standardize Bower distribution by adding dist folder with minified files

### ISSUE THREAD

**Issue by ste93cry** [makeusabrew/bootbox#496] opened 2016-02-14 19:26 UTC
Usually Bower downloads have a `dist` folder where all production assets are located, possibly minified. Any plan on doing it too for bootbox?

**Comment by makeusabrew** [comment] 2016-09-23 13:07
Yep, on the list... promise...

**Comment by makeusabrew** [comment] 2016-09-26 09:19
Dupe of #208

**Closed by makeusabrew** 2016-09-26 09:19 UTC

**Comment by chule143** [comment] 2016-11-22 22:09
any news on this?, the package from Bower doesn't come with the minified version
