### ISSUE TITLE
Locale is not working into my project

### ISSUE THREAD

**Issue by accarvajal** [makeusabrew/bootbox#754] opened 2020-05-15 23:25 UTC
Hi, 

I'm developing an asp.net core 2.2 web app, and I'm using the leatest version of bootbox, bootbox locales, bootstrap 3.3.7 and jquery, all loaded in the right order, in the head of the html page. Just after the script files, is referenced I'm running bootbox.setDefaults for locale without success, even by using bootbox.setLocale("es"). Also, I tried setting the locale into bootbox.Dialog with no success. Button are shown in english. 

    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    @{
          ViewData["Cultura"] = System.Globalization.CultureInfo.CurrentCulture.ToString();
     }
    <link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <link href="/css/awesome-bootstrap-checkbox.css" rel="stylesheet">
    <link href="/lib/floating-form-labels/css/floatingFormLabels.css" rel="stylesheet">
    <link href="/lib/fontawesome/dist/css/all.min.css" rel="stylesheet">
    <link href="/lib/bootbox/dist/bootbox.css" rel="stylesheet">
    <link href="/lib/kendo-ui/styles/kendo.common-material.min.css" rel="stylesheet" type="text/css">
    <link href="/lib/kendo-ui/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css">
    <link href="/lib/kendo-ui/styles/kendo.material.min.css" rel="stylesheet" type="text/css">
    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/lib/floating-form-labels/dist/floatingFormLabels.min.js"></script>
    <script src="/lib/bootbox/dist/bootbox.js"></script>
    <script src="/lib/bootbox/dist/bootbox.locales.js"></script>
    <script src="/lib/kendo-ui/js/angular.min.js"></script>
    <script src="/lib/kendo-ui/js/jszip.min.js"></script>
    <script src="/lib/kendo-ui/js/kendo.all.min.js"></script>
    <script src="/lib/kendo-ui/js/kendo.aspnetmvc.min.js"></script>
    <script src="/lib/kendo-ui/js/cultures/kendo.culture.es-CO.min.js"></script>
    <script src="/lib/kendo-ui/js/messages/kendo.messages.es-CO.min.js"></script>
    <script src="/js/site.js?v=0hveRxpBJQe8_z_J0ki8shXpha1gnQ6wvN7qmpOQs00"></script>

    <script type="text/javascript">
        var culture = "@ViewData["Cultura"]";
        var language = "@ViewData["Cultura"].ToString().Substring(0, 2)";

        kendo.culture(culture);
        bootbox.setLocale(language);
    </script>    
        <link href="/css/site.css?v=I6YblCQ52zn93BQRrY1f-gaHn1JoNvQgxUJGPnIK80g" rel="stylesheet">
  
    </head>

**Comment by tiesont** [comment] 2020-05-16 09:59
Bootbox doesn't have a CSS file - are you sure you're referencing the correct files?

**Comment by accarvajal** [comment] 2020-05-17 20:08
> Bootbox doesn't have a CSS file - are you sure you're referencing the correct files?

Bootbox.css is just my own custom styles. Yes, I'm referencing the correct files:

![image](https://user-images.githubusercontent.com/20478780/82158864-2a238d00-9850-11ea-88c9-4233c1200a68.png)

**Comment by tiesont** [comment] 2020-05-17 20:24
I haven't been able to reproduce this. Out of curiosity, does it work if you load just the `bootbox.all.js` file (in place of the two separate files)? Are you seeing any errors in the developer console?

**Comment by accarvajal** [comment] 2020-05-24 20:40
> I haven't been able to reproduce this. Out of curiosity, does it work if you load just the `bootbox.all.js` file (in place of the two separate files)? Are you seeing any errors in the developer console?

Hi, same issue, curiously I'm not seeing any errors in console, since I'm developing a SPA in asp.net core, maybe I'm guessing that problem is related with a partialView called into _Layout which provides all css and js files, or maybe could be some other js which is causing the issue, I'm not sure.

**Comment by tiesont** [comment] 2020-09-29 00:17
Closing this as "Can't reproduce". If you can provide a sample project that demonstrates what you're seeing, we can reopen.

**Closed by tiesont** 2020-09-29 00:17 UTC
Labels: Bug?
