### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by odahcam** [makeusabrew/bootbox#619] opened 2017-08-11 18:21 UTC
Bootstrap 4 beta has launched today. So what's the possibility of updating a BS3 + bootbox UI to BS4?

**Comment by tiesont** [comment] 2017-08-11 18:33
Won't happen until/unless we move forward with a 5.0 release, but (assuming nothing changed between Alpha 6 and Beta) I have noted the changes I had to make in #566.

I'll take a look and see if anything major has changed in the Beta for modals, but that's probably the best you'll get for now.

**Comment by tiesont** [comment] 2017-08-18 23:15
Closing as a dupe of #566 - please comment there if you need clarification.

**Closed by tiesont** 2017-08-18 23:15 UTC
