### ISSUE TITLE
Callback functions of custom dialogs are performed more than once in fast clicks

### ISSUE THREAD

**Issue by wellyfrs** [makeusabrew/bootbox#674] opened 2018-07-26 15:01 UTC
### Reproduce

1. Access http://bootboxjs.com/examples.html#bb-custom-dialog.
2. Click on "Run example" button (section of "Custom dialog, with buttons and button callbacks").
3. Click twice **quickly** on the OK button ("I'm a custom OK button!").
4. Note that two messages are displayed, one after the other.

Running the same callback function twice or more can be a problem in some cases. Should not the first click prevent additional clicks by default?

**OS:** Ubuntu 18.04 LTS 64-bit
**Browser:** Google Chrome 67.0.3396.99 64-bit

**Comment by tiesont** [comment] 2018-07-27 03:37
This was reported previously, in #514, and was supposed to have been fixed - I can't reproduce this at the moment, but I'm also not running any version of Linux. Not exactly sure when I'll have time to look any deeper into this, but I won't close this, either, if someone else can confirm.

**Comment by wellyfrs** [comment] 2018-07-27 12:39
@tiesont, you can easily reproduce this by pressing "enter" twice instead of the clicks.

Try this demo: https://jsfiddle.net/wellyfrs/ajrbpgo5

**Comment by tiesont** [comment] 2018-07-27 17:59
Okay, I can see that now. Not sure what the best recourse is; the code does remove the event handlers, but apparently not quick enough. I'll have to see if there is some way of dumping any clicks beyond the first. Might have to wait until after 5.0 is released, though.

**Closed** 2019-02-27 19:26 UTC
Labels: Bug?, Task
